version: '3'

services:
  db:
    image: mysql:5.6
    container_name: kyrosb01_db
    networks:
      - backend
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=kyrosb01
    ports: 
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    container_name: kyrosb01_web
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - frontend
      - backend
    environment:
      JDBC_URL: jdbc:mysql://kyrosb01_db:3306/kyrosb01?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: root
      JDBC_PASS: 
    ports:
      - "80:8080"
    volumes: 
      - ./tomcat/webapps:/usr/local/tomcat/webapps

networks:
  frontend:
  backend:

volumes:
  mysql-data: